backend:
  name: github
  repo: gamalkhalaf/gamalkhalaf.github.io
  branch: main
  base_url: https://netlify-cms-github-oauth-provider-q.vercel.app
media_folder: docs/assets/images
public_folder: /assets/images
collections:
- name: subjects
  label: المواد الدراسية
  folder: docs/admin/subjects
  create: true
  slug: '{{fields.slug}}'
  extension: yml
  format: yaml
  fields:
  - label: اسم المادة
    name: label
    widget: string
  - label: المعرف (slug)
    name: slug
    widget: string
- name: imlaa_lessons
  label: دروس في الاملاء
  folder: docs/imlaa
  create: true
  slug: '{{slug}}'
  fields:
  - label: عنوان الدرس
    name: title
    widget: string
  - label: تفعيل التشفير وحماية الصفحة
    name: encrypt
    widget: boolean
    default: true
  - label: محتوى الدرس
    name: body
    widget: markdown
- name: nahw_lessons
  label: ' دروس في النحو'
  folder: docs/nahw
  create: true
  slug: '{{slug}}'
  fields:
  - label: عنوان الدرس
    name: title
    widget: string
  - label: تفعيل التشفير وحماية الصفحة
    name: encrypt
    widget: boolean
    default: true
  - label: محتوى الدرس
    name: body
    widget: markdown
- name: qiraa_lessons
  label: ' دروس في القراءة'
  folder: docs/qiraa
  create: true
  slug: '{{slug}}'
  fields:
  - label: عنوان الدرس
    name: title
    widget: string
  - label: تفعيل التشفير وحماية الصفحة
    name: encrypt
    widget: boolean
    default: true
  - label: محتوى الدرس
    name: body
    widget: markdown
