backend:
  name: github
  repo: gamalkhalaf/gamalkhalaf.github.io
  branch: main
  base_url: https://netlify-cms-github-oauth-provider-q.vercel.app
media_folder: docs/assets/images
public_folder: /assets/images
collections:
- name: subjects
  label: المواد الدراسية
  folder: docs/admin/subjects
  create: true
  slug: '{{fields.slug}}'
  extension: yml
  format: yaml
  fields:
  - label: اسم المادة
    name: label
    widget: string
  - label: المعرف (slug)
    name: slug
    widget: string
