backend:
    name: test
  # name: git-gateway
  # branch: main

site_url: https://sweet-baklava-619a0f.netlify.app

media_folder: "docs/assets/images"
public_folder: "/assets/images"

collections:
  - name: "nahw_lessons"
    label: "دروس في النحو"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "عنوان الدرس", name: "title", widget: "string" }
      - { label: "تفعيل التشفير وحماية الصفحة", name: "encrypt", widget: "boolean", default: true }
      - { label: "محتوى الدرس", name: "body", widget: "markdown" }